### ISSUE TITLE
Add color space for ACEScg

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/color#14]
See:

* https://docs.acescentral.com/specifications/acescg/

Also:

* https://acescolorspace.com
* https://www.chaos.com/blog/everything-you-need-to-know-about-acescg

**Comment by MightyBurger** [comment]
I started looking into this. Here are some thoughts. Correct me on anything I got wrong.

The ACES spec defines ACEScg with respect to ACES2065-1, which is the "primary" color space in the ACES system. The ACES2065-1 color space has a wider gamut than ACEScg, which is already wide. [This PDF](https://pub.smpte.org/pub/st2065-1/st2065-1-2021.pdf) defines ACES2065-1 and is a good resource. Importantly, the PDF has a transformation matrix to convert between ACES2065-1 and CIE XYZ (I'm assuming D65; I'd have to dig more to confirm).

One part to figure out is converting to and from linear sRGB. This seems really simple at a glance. We could take the linear sRGB to CIE XYZ matrix, CIE XYZ to ACES2065-1 matrix, and the ACES2065-1 to ACEScg matrix, and multiply them ahead of time to get just a single transformation matrix. Same story with the inverse matrices. I believe these are all linear color spaces, so there's no reason this shouldn't work... anything obvious I'm missing?

There may be value in adding the ACES2065-1 color space in addition to ACEScg.

There's perhaps some bikeshedding to have on the naming. The dash in ACES2065-1 makes naming the tags a little annoying.

A couple ideas:

- `ACES2065_1` and `ACEScg` (Not consistent with capitalization of the other color spaces)
- `Aces2065_1` and `AcesCg` (Not a fan of the capital C in Cg)

I considered the names AP0 and AP1, which are the primaries of each color space. There's some precedence to this: DaVinci Resolve calls ACES2065-1 "ACES (AP0)" and ACESsg "ACES (AP1)". That said, I don't think these names are a good idea. They would lead to ambiguity since the nonlinear color spaces ACEScc and ACEScct also use the AP1 primaries.

I had some fun looking into this. I have a lot going on this week and I might need to do a little more learning than some of you might, so don't let me lick this cookie if you need this color space fast. Otherwise, I think I'd enjoy trying to implement these color spaces.

**Comment by raphlinus** [comment]
You're on the right track about just multiplying the matrices together. Structurally, the color space should look very similar to `XyzD50`. As I said on Mastodon, all linear color spaces are alike, but each nonlinear colorspace is nonlinear in its own way.

I don't have strong feelings about naming, but `AcesCg` feels most Rust-like to me. I also don't have strong feelings about other related color spaces (they seem to have quite a few), but the main reason to choose ACEScg is that it's the central color space in [nanocolor](https://github.com/meshula/Nanocolor).

Glad to have you onboard, and learning is part of the Linebender mission, so don't feel shy. I don't consider this a blocker for 0.1.

**Comment by MightyBurger** [comment]
Thank you very much! 😄

**Comment by MightyBurger** [comment]
It looks like my assumption of XYZ D65 was incorrect. I tried converting Linear sRGB to ACEScg as described above and got unacceptable error compared to [ACES's own calculator](https://acescolorspace.com/rgb#). The source of error was converting Linear sRGB to XYZ.

The problem is the white point. It's not D65, D50, or any of the "canonical" CIE white points. Rather, it's something very close to D60. I skimmed through [this page](https://docs.acescentral.com/tb/white-point#reasons-for-the-d60-like-white-point) and it seems valuable. I'll give this a closer look later this week or weekend.

I think the next step is figuring out conversion from Linear sRGB to XYZ "D60-ish", which will be a little learning from me. I was able to sus out this conversion matrix from the aforementioned calculator and successfully converted from Linear sRGB to ACEScg, but I'd like to do this properly.
