### ISSUE TITLE
Merge `CSSColor` and `TaggedColor`

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/color#21]
Raph leans towards keeping the `TaggedColor` name but with merged functionality. (I think.)

**Comment by nicoburns** [comment]
We could consider `DynamicColor` as a name, by analogy to the `DynamicImage` type in the `image` crate.

This crate seems very similar in its position in the ecosystem to `image` (and similar in its structure if you replace image formats with color spaces). So some consistency between these crates might be nice.

**Comment by raphlinus** [comment]
I'm ok with DynamicColor. I considered and rejected DynColor because it suggests dyn trait, but I agree that the parallel to `image` makes sense here.

Incidentally, I have the merge in my tree, on top of #11 because I wanted to avoid too many merge conflicts. Easiest thing is for me to post it when #11 is merged, though I can post it earlier if people are eager to see.
